### ISSUE TITLE
Configure eslint, prettier, airbnb

### ISSUE THREAD

**Issue by kelvin-muchiri** [onaio/gisida-react#131]

**Comment by cKellyDesign** [comment]
It seems like this is linting and throwing errors when trying to compile/develop gisida-react, can we instead have this only running with `yarn lint` instead? We could add this step to the pre-commit hook as well (like in Reveal), but I think we need to be able to compile imperfect code.

**Comment by cKellyDesign** [comment]
@kelvin-muchiri can this be closed? #132?
